# nginx.conf
server {
    listen 80;
    server_name laopioneer.com www.laopioneer.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name laopioneer.com www.laopioneer.com;

    ssl_certificate /etc/letsencrypt/live/www.laopioneer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.laopioneer.com/privkey.pem;
    ssl_certificate /etc/letsencrypt/live/laopioneer.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/laopioneer.com/privkey.pem;

    location /api/ {
        proxy_pass http://backend:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }
}